# Generated by Django 3.0.4 on 2020-04-03 15:14

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_auto_20200320_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
