# Generated by Django 3.0.4 on 2020-04-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='subject',
            field=models.CharField(max_length=50),
        ),
    ]
