# Generated by Django 3.0.4 on 2020-05-14 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0011_auto_20200513_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='start_hour',
            field=models.TimeField(blank=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='check_in',
            field=models.DateField(blank=True, default='15-05-2020'),
        ),
    ]
