# Generated by Django 3.0.4 on 2020-05-14 21:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0012_auto_20200515_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='start_hour',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
