# Generated by Django 3.0.4 on 2020-05-15 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0013_auto_20200515_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='start_hour',
        ),
    ]
