# Generated by Django 3.0.4 on 2020-05-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0014_remove_reservation_start_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='start_hour',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
