# Generated by Django 3.0.4 on 2020-05-14 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0015_reservation_hours2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='hours2',
        ),
    ]
