# Generated by Django 3.0.4 on 2020-05-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0015_reservation_start_hour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='start_hour',
            new_name='destination_to',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='hours',
            new_name='distance',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='check_in',
        ),
        migrations.AddField(
            model_name='reservation',
            name='date',
            field=models.DateField(blank=True, default='2020-05-23'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='kisi_sayisi',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='option',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='reservation',
            name='start_from',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
