# Generated by Django 3.0.4 on 2020-05-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0017_auto_20200523_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='address',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
