# Generated by Django 3.0.4 on 2020-05-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0019_auto_20200528_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='return_date',
            field=models.DateTimeField(blank=True, default='2020-05-28'),
            preserve_default=False,
        ),
    ]
