# Generated by Django 3.0.4 on 2020-05-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0020_reservation_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='return_date',
            field=models.DateField(blank=True),
        ),
    ]
