# Generated by Django 3.0.4 on 2020-05-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0021_auto_20200528_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='return_date',
            field=models.DateField(blank=True, default=None),
        ),
    ]
