# Generated by Django 3.0.4 on 2020-05-14 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0021_remove_reservation_start_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='start_hour',
            field=models.TimeField(blank=True, default='00:00'),
        ),
    ]
