# Generated by Django 3.0.4 on 2020-05-28 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0022_auto_20200528_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='option',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='return_date',
        ),
    ]
