# Generated by Django 3.0.4 on 2020-05-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0023_auto_20200528_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='time',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
