# Generated by Django 3.0.4 on 2020-05-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0025_reservation_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='adminnote',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
