# Generated by Django 3.0.4 on 2020-05-14 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0025_reservation_start_hour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='start_hour',
        ),
    ]
