# Generated by Django 3.0.4 on 2020-05-14 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0027_reservation_start_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='start_hour',
            field=models.TimeField(blank=True),
        ),
    ]
