# Generated by Django 3.0.4 on 2020-05-14 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0028_auto_20200515_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='start_hour',
            field=models.IntegerField(blank=True),
        ),
    ]
