# Generated by Django 3.0.4 on 2020-05-14 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0029_auto_20200515_0222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='start_hour',
        ),
    ]
