# Generated by Django 3.0.4 on 2020-05-14 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0030_remove_reservation_start_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='start_hours',
            field=models.IntegerField(blank=True, default=12),
            preserve_default=False,
        ),
    ]
