# Generated by Django 3.0.4 on 2020-05-14 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0031_reservation_start_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='start_hours',
        ),
    ]
